"""Remove double inicialization error for Base

Revision ID: c9c31a8548d0
Revises: 2cdc463620e0
Create Date: 2025-01-19 19:01:17.463893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9c31a8548d0'
down_revision: Union[str, None] = '2cdc463620e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
